<?php /* Smarty version 2.6.10, created on 2020-07-15 08:59:28
         compiled from Welcome.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%09^099^0997F726%%Welcome.tpl.inc'] = 'ede278d21dcfe01d4c0c8af44f886d9a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Welcome.tpl', 6, false),array('function', 'url', 'Welcome.tpl', 189, false),)), $this); ?>
<?php
function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/resources/css/ext-all.css"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/adapter/ext/ext-base.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ext-all.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/Portal.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/PortalColumn.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/Portlet.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/css/Portal.css"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Common.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_9(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/thickbox/thickbox.js"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_10(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/thickbox/thickbox.css"), $_smarty);
}


function _smarty_tplfunc_ede278d21dcfe01d4c0c8af44f886d9a_11(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'Trade_Order','action' => 'Trace'), $_smarty);
}



?>
