<?php /* Smarty version 2.6.10, created on 2020-07-15 08:59:26
         compiled from BossReport.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%24^24D^24D6BBC5%%BossReport.tpl.inc'] = '7c70a3faf434d719a324e5e557a33821';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'BossReport.tpl', 6, false),array('modifier', 'json_encode', 'BossReport.tpl', 40, false),)), $this); ?>
<?php
function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Calendar/WdatePicker.js"), $_smarty);
}


function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.1.9.1.js"), $_smarty);
}


function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/css/bootstrap.css"), $_smarty);
}


function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/js/bootstrap.min.js"), $_smarty);
}


function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/BtGrid/btGrid.2.0.js"), $_smarty);
}


function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/BtGrid/btGrid.css"), $_smarty);
}


function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/layer/layer.js"), $_smarty);
}


function _smarty_tplfunc_7c70a3faf434d719a324e5e557a33821_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/echart/echarts.min.js"), $_smarty);
}



?>
