<?php /* Smarty version 2.6.10, created on 2020-07-15 08:59:28
         compiled from Search/clientId.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%2F^2FE^2FE0CAEB%%clientId.tpl.inc'] = '41526d2fb8e73df621ab8e62a6e24b08';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Search/clientId.tpl', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_41526d2fb8e73df621ab8e62a6e24b08_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Clientoptions','selected' => $_smarty->_tpl_vars['arr_condition']['clientId'],'isLimit' => '1'), $_smarty);
}



?>
