<?php /* Smarty version 2.6.10, created on 2020-07-15 08:59:24
         compiled from Main.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%8B^8BA^8BAC94BE%%Main.tpl.inc'] = '593c5046580b34a7f70ec9bb2e5b0c64';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Main.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'systemV'), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/resources/css/ext-all.css"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/main1.css"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/adapter/ext/ext-base.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ext-all.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/TabCloseMenu.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/thickbox/thickbox.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.1.9.1.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_9(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/layer3.1.1/layer.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_10(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "http://sev1.eqinfo.com.cn/login_server/resource/serverRemind/robot.css"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_11(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/thickbox/thickbox.css"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_12(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/ymPrompt.js"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_13(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/skin/qq/ymPrompt.css"), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_14(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'systemV'), $_smarty);
}


function _smarty_tplfunc_593c5046580b34a7f70ec9bb2e5b0c64_15(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Servtel'), $_smarty);
}



?>
