<?php /* Smarty version 2.6.10, created on 2020-07-15 08:59:28
         compiled from Search/huaxing.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%D8^D8D^D8D4B390%%huaxing.tpl.inc'] = '009efaa4f1ed03e41b3b2c40d30bf92b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Search/huaxing.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_009efaa4f1ed03e41b3b2c40d30bf92b_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Sysparam','item' => 'manuCodeName'), $_smarty);
}


function _smarty_tplfunc_009efaa4f1ed03e41b3b2c40d30bf92b_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Sysparam','item' => 'manuCodeName'), $_smarty);
}



?>
